/*
Deployment script for MusicDb

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;

GO

PRINT N'Creating [dbo].[Album]...';


GO
CREATE TABLE [dbo].[Album] (
    [AlbumId]             BIGINT             IDENTITY (1, 1) NOT NULL,
    [Slug]                NVARCHAR (250)     NOT NULL,
    [Type]                NVARCHAR (25)      NOT NULL,
    [Href]                NVARCHAR (2000)    NOT NULL,
    [Id]                  BIGINT             NOT NULL,
    [ArtistName]          NVARCHAR (350)     NOT NULL,
    [Copyright]           NVARCHAR (MAX)     NULL,
    [IsComplete]          BIT                NOT NULL,
    [IsSingle]            BIT                NOT NULL,
    [Name]                NVARCHAR (350)     NOT NULL,
    [RecordLabel]         NVARCHAR (MAX)     NULL,
    [TrackCount]          INT                NOT NULL,
    [IsMasteredForItunes] BIT                NOT NULL,
    [ContentRating]       NVARCHAR (50)      NULL,
    [ReleaseDate]         DATETIMEOFFSET (7) NULL,
    [DescShort]           NVARCHAR (MAX)     NULL,
    [DescStandard]        NVARCHAR (MAX)     NULL,
    [ImageHeight]         INT                NULL,
    [ImageWidth]          INT                NULL,
    [ImageURL]            NVARCHAR (2000)    NULL,
    CONSTRAINT [PK_dbo.Album] PRIMARY KEY CLUSTERED ([AlbumId] ASC)
);


GO
PRINT N'Creating [dbo].[Album].[IX_Album_Slug]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Album_Slug]
    ON [dbo].[Album]([Slug] ASC);


GO
PRINT N'Creating [dbo].[AlbumGenre]...';


GO
CREATE TABLE [dbo].[AlbumGenre] (
    [AlbumId] BIGINT NOT NULL,
    [GenreId] BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.AlbumGenre] PRIMARY KEY CLUSTERED ([AlbumId] ASC, [GenreId] ASC)
);


GO
PRINT N'Creating [dbo].[AppAnalyticsEvent]...';


GO
CREATE TABLE [dbo].[AppAnalyticsEvent] (
    [AppAnalyticsEventId] BIGINT             IDENTITY (1, 1) NOT NULL,
    [RemoteIPAddress]     NVARCHAR (100)     NOT NULL,
    [RemoteIpType]        NVARCHAR (6)       NOT NULL,
    [UserId]              NVARCHAR (256)     NULL,
    [SessionId]           NVARCHAR (140)     NULL,
    [Method]              NVARCHAR (12)      NOT NULL,
    [UrlPath]             NVARCHAR (1024)    NOT NULL,
    [EventDateTime]       DATETIMEOFFSET (7) NOT NULL,
    [ResourceId]          BIGINT             NOT NULL,
    [ResourceType]        INT                NOT NULL,
    [EventType]           INT                NOT NULL,
    CONSTRAINT [PK_dboAppAnalyticsEvent] PRIMARY KEY CLUSTERED ([AppAnalyticsEventId] ASC)
);


GO
PRINT N'Creating [dbo].[AppAnalyticsEvent].[IX_AppAnalyticsEvent_IPResourceEvent]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_AppAnalyticsEvent_IPResourceEvent]
    ON [dbo].[AppAnalyticsEvent]([RemoteIPAddress] ASC, [ResourceType] ASC, [EventType] ASC, [UserId] ASC);


GO
PRINT N'Creating [dbo].[AppAnalyticsRequest]...';


GO
CREATE TABLE [dbo].[AppAnalyticsRequest] (
    [AppAnalyticsRequestId] BIGINT             IDENTITY (1, 1) NOT NULL,
    [RemoteIPAddress]       NVARCHAR (100)     NOT NULL,
    [RemoteIpType]          NVARCHAR (6)       NOT NULL,
    [UserId]                NVARCHAR (256)     NULL,
    [SessionId]             NVARCHAR (140)     NULL,
    [Method]                NVARCHAR (12)      NOT NULL,
    [UrlPath]               NVARCHAR (1024)    NOT NULL,
    [EventDateTime]         DATETIMEOFFSET (7) NOT NULL,
    [City]                  NVARCHAR (200)     NULL,
    [CountryCode]           NVARCHAR (12)      NOT NULL,
    [CountryName]           NVARCHAR (200)     NOT NULL,
    [IsDesktop]             BIT                NOT NULL,
    [IsMobile]              BIT                NOT NULL,
    [IsTablet]              BIT                NOT NULL,
    [IsTouchEnabled]        BIT                NOT NULL,
    [IsWebSocket]           BIT                NOT NULL,
    [Latitude]              FLOAT (53)         NULL,
    [Longitude]             FLOAT (53)         NULL,
    [DeviceName]            NVARCHAR (125)     NULL,
    [ModelName]             NVARCHAR (125)     NULL,
    [OsName]                NVARCHAR (50)      NULL,
    [PostalCode]            NVARCHAR (25)      NULL,
    [Referer]               NVARCHAR (1024)    NULL,
    [RegionCode]            NVARCHAR (12)      NULL,
    [RegionName]            NVARCHAR (200)     NULL,
    [TimeZone]              NVARCHAR (80)      NULL,
    [UserAgent]             NVARCHAR (512)     NULL,
    CONSTRAINT [PK_dbo.AppAnalyticsRequest] PRIMARY KEY CLUSTERED ([AppAnalyticsRequestId] ASC)
);


GO
PRINT N'Creating [dbo].[AppAnalyticsRequest].[IX_AppAnalyticsRequest_RemoteIP_EventDate]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_AppAnalyticsRequest_RemoteIP_EventDate]
    ON [dbo].[AppAnalyticsRequest]([RemoteIPAddress] ASC, [EventDateTime] ASC);


GO
PRINT N'Creating [dbo].[AppAnalyticsTotal]...';


GO
CREATE TABLE [dbo].[AppAnalyticsTotal] (
    [AppAnalyticsTotalId] BIGINT IDENTITY (1, 1) NOT NULL,
    [ResourceId]          BIGINT NOT NULL,
    [ResourceType]        INT    NOT NULL,
    [EventType]           INT    NOT NULL,
    [TotalCount]          BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.AppAnalyticsTotals] PRIMARY KEY CLUSTERED ([AppAnalyticsTotalId] ASC)
);


GO
PRINT N'Creating [dbo].[AppAnalyticsTotal].[IX_AppAnalyticsTotal_IdResourceEvent]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_AppAnalyticsTotal_IdResourceEvent]
    ON [dbo].[AppAnalyticsTotal]([ResourceType] ASC, [EventType] ASC, [ResourceId] ASC);


GO
PRINT N'Creating [dbo].[Artist]...';


GO
CREATE TABLE [dbo].[Artist] (
    [ArtistId]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [Slug]         NVARCHAR (250)  NOT NULL,
    [Type]         NVARCHAR (25)   NOT NULL,
    [Href]         NVARCHAR (2000) NOT NULL,
    [Id]           BIGINT          NOT NULL,
    [Name]         NVARCHAR (350)  NOT NULL,
    [BornOrFormed] NVARCHAR (MAX)  NULL,
    [ArtistBio]    NVARCHAR (MAX)  NULL,
    [Origin]       NVARCHAR (MAX)  NULL,
    [DescShort]    NVARCHAR (MAX)  NULL,
    [DescStandard] NVARCHAR (MAX)  NULL,
    [ImageHeight]  INT             NULL,
    [ImageWidth]   INT             NULL,
    [ImageURL]     NVARCHAR (2000) NULL,
    [ArtistToken]  INT             NOT NULL,
    CONSTRAINT [PK_dbo.Artist] PRIMARY KEY CLUSTERED ([ArtistId] ASC)
);


GO
PRINT N'Creating [dbo].[Artist].[IX_Artist_Slug]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Artist_Slug]
    ON [dbo].[Artist]([Slug] ASC);


GO
PRINT N'Creating [dbo].[ArtistAlbum]...';


GO
CREATE TABLE [dbo].[ArtistAlbum] (
    [ArtistId] BIGINT NOT NULL,
    [AlbumId]  BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.ArtistAlbum] PRIMARY KEY CLUSTERED ([ArtistId] ASC, [AlbumId] ASC)
);


GO
PRINT N'Creating [dbo].[ArtistGenre]...';


GO
CREATE TABLE [dbo].[ArtistGenre] (
    [ArtistId] BIGINT NOT NULL,
    [GenreId]  BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.ArtistGenre] PRIMARY KEY CLUSTERED ([ArtistId] ASC, [GenreId] ASC)
);


GO
PRINT N'Creating [dbo].[ArtistPlaylist]...';


GO
CREATE TABLE [dbo].[ArtistPlaylist] (
    [PlaylistId] BIGINT NOT NULL,
    [ArtistId]   BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.ArtistPlaylist] PRIMARY KEY CLUSTERED ([PlaylistId] ASC, [ArtistId] ASC)
);


GO
PRINT N'Creating [dbo].[ArtistSong]...';


GO
CREATE TABLE [dbo].[ArtistSong] (
    [ArtistId] BIGINT NOT NULL,
    [SongId]   BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.ArtistSong] PRIMARY KEY CLUSTERED ([ArtistId] ASC, [SongId] ASC)
);


GO
PRINT N'Creating [dbo].[AspNetRoleClaims]...';


GO

PRINT N'Creating [dbo].[Genre]...';


GO
CREATE TABLE [dbo].[Genre] (
    [GenreId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [Id]         BIGINT          NOT NULL,
    [Name]       NVARCHAR (350)  NOT NULL,
    [Slug]       NVARCHAR (250)  NOT NULL,
    [ParentId]   BIGINT          NULL,
    [ParentName] NVARCHAR (350)  NULL,
    [Type]       NVARCHAR (25)   NOT NULL,
    [Href]       NVARCHAR (2000) NOT NULL,
    CONSTRAINT [PK_dbo.Genre] PRIMARY KEY CLUSTERED ([GenreId] ASC)
);


GO
PRINT N'Creating [dbo].[Genre].[IX_Genre_AppleId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Genre_AppleId]
    ON [dbo].[Genre]([Id] ASC);


GO
PRINT N'Creating [dbo].[Genre].[IX_Genre_Slug]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Genre_Slug]
    ON [dbo].[Genre]([Slug] ASC);


GO
PRINT N'Creating [dbo].[Lyric]...';


GO
CREATE TABLE [dbo].[Lyric] (
    [LyricId]     BIGINT          NOT NULL,
    [Type]        NVARCHAR (25)   NOT NULL,
    [Href]        NVARCHAR (2000) NOT NULL,
    [Id]          BIGINT          NOT NULL,
    [DisplayType] INT             NOT NULL,
    [Ttml]        NVARCHAR (MAX)  NULL,
    [Html]        NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_dbo.Lyric] PRIMARY KEY CLUSTERED ([LyricId] ASC)
);


GO
PRINT N'Creating [dbo].[Performer]...';


GO
CREATE TABLE [dbo].[Performer] (
    [PerformerId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [Slug]           NVARCHAR (250)  NOT NULL,
    [Type]           NVARCHAR (25)   NOT NULL,
    [Href]           NVARCHAR (2000) NOT NULL,
    [Name]           NVARCHAR (350)  NOT NULL,
    [BornOrFormed]   NVARCHAR (500)  NULL,
    [PerformerBio]   NVARCHAR (MAX)  NULL,
    [Origin]         NVARCHAR (MAX)  NULL,
    [DescShort]      NVARCHAR (MAX)  NULL,
    [DescStandard]   NVARCHAR (MAX)  NULL,
    [ImageHeight]    INT             NULL,
    [ImageWidth]     INT             NULL,
    [ImageURL]       NVARCHAR (2000) NULL,
    [PerformerToken] INT             NOT NULL,
    CONSTRAINT [PK_dbo.Performer] PRIMARY KEY CLUSTERED ([PerformerId] ASC)
);


GO
PRINT N'Creating [dbo].[Performer].[IX_Performer_Slug]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Performer_Slug]
    ON [dbo].[Performer]([Slug] ASC);


GO
PRINT N'Creating [dbo].[PerformerAlbum]...';


GO
CREATE TABLE [dbo].[PerformerAlbum] (
    [PerformerId] BIGINT NOT NULL,
    [AlbumId]     BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.PerformerAlbum] PRIMARY KEY CLUSTERED ([PerformerId] ASC, [AlbumId] ASC)
);


GO
PRINT N'Creating [dbo].[PerformerGenre]...';


GO
CREATE TABLE [dbo].[PerformerGenre] (
    [PerformerId] BIGINT NOT NULL,
    [GenreId]     BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.PerformerGenre] PRIMARY KEY CLUSTERED ([PerformerId] ASC, [GenreId] ASC)
);


GO
PRINT N'Creating [dbo].[PerformerPlaylist]...';


GO
CREATE TABLE [dbo].[PerformerPlaylist] (
    [PerformerId] BIGINT NOT NULL,
    [PlaylistId]  BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.PerformerPlaylist] PRIMARY KEY CLUSTERED ([PerformerId] ASC, [PlaylistId] ASC)
);


GO
PRINT N'Creating [dbo].[PerformerSong]...';


GO
CREATE TABLE [dbo].[PerformerSong] (
    [PerformerId] BIGINT NOT NULL,
    [SongId]      BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.PerformerSong] PRIMARY KEY CLUSTERED ([PerformerId] ASC, [SongId] ASC)
);


GO
PRINT N'Creating [dbo].[PerformerUser]...';


GO
CREATE TABLE [dbo].[PerformerUser] (
    [PerformerId] BIGINT         NOT NULL,
    [UserId]      NVARCHAR (128) NOT NULL,
    CONSTRAINT [PK_dbo.PerformerUser] PRIMARY KEY CLUSTERED ([PerformerId] ASC, [UserId] ASC)
);


GO
PRINT N'Creating [dbo].[Playlist]...';


GO
CREATE TABLE [dbo].[Playlist] (
    [PlaylistId]       BIGINT             IDENTITY (1, 1) NOT NULL,
    [Slug]             NVARCHAR (250)     NOT NULL,
    [Type]             NVARCHAR (25)      NOT NULL,
    [Href]             NVARCHAR (2000)    NOT NULL,
    [Id]               BIGINT             NOT NULL,
    [CuratorName]      NVARCHAR (350)     NOT NULL,
    [Name]             NVARCHAR (350)     NOT NULL,
    [PlaylistType]     NVARCHAR (125)     NOT NULL,
    [Url]              NVARCHAR (2000)    NOT NULL,
    [ParamId]          NVARCHAR (700)     NOT NULL,
    [IsChart]          BIT                NOT NULL,
    [TrackCount]       INT                NOT NULL,
    [LastModifiedDate] DATETIMEOFFSET (7) NULL,
    [DescShort]        NVARCHAR (MAX)     NULL,
    [DescStandard]     NVARCHAR (MAX)     NULL,
    [ImageHeight]      INT                NULL,
    [ImageWidth]       INT                NULL,
    [ImageURL]         NVARCHAR (2000)    NULL,
    CONSTRAINT [PK_dbo.Playlist] PRIMARY KEY CLUSTERED ([PlaylistId] ASC)
);


GO
PRINT N'Creating [dbo].[Playlist].[IX_Playlist_AppleId]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Playlist_AppleId]
    ON [dbo].[Playlist]([Id] ASC);


GO
PRINT N'Creating [dbo].[Playlist].[IX_Playlist_Slug]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Playlist_Slug]
    ON [dbo].[Playlist]([Slug] ASC);


GO
PRINT N'Creating [dbo].[PlaylistGenre]...';


GO
CREATE TABLE [dbo].[PlaylistGenre] (
    [PlaylistId] BIGINT NOT NULL,
    [GenreId]    BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.PlaylistGenre] PRIMARY KEY CLUSTERED ([PlaylistId] ASC, [GenreId] ASC)
);


GO
PRINT N'Creating [dbo].[PlaylistSong]...';


GO
CREATE TABLE [dbo].[PlaylistSong] (
    [PlaylistId] BIGINT NOT NULL,
    [SongId]     BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.PlaylistSong] PRIMARY KEY CLUSTERED ([PlaylistId] ASC, [SongId] ASC)
);


GO
PRINT N'Creating [dbo].[Song]...';


GO
CREATE TABLE [dbo].[Song] (
    [SongId]              BIGINT             IDENTITY (1, 1) NOT NULL,
    [Slug]                NVARCHAR (250)     NOT NULL,
    [Type]                NVARCHAR (25)      NOT NULL,
    [Href]                NVARCHAR (2000)    NOT NULL,
    [Id]                  BIGINT             NOT NULL,
    [AlbumName]           NVARCHAR (350)     NOT NULL,
    [ArtistName]          NVARCHAR (350)     NOT NULL,
    [ComposerName]        NVARCHAR (350)     NULL,
    [DiskNumber]          INT                NOT NULL,
    [DurationInMillis]    INT                NOT NULL,
    [Isrc]                NVARCHAR (150)     NULL,
    [MovementCount]       INT                NOT NULL,
    [MovementName]        NVARCHAR (350)     NULL,
    [MovementNumber]      INT                NOT NULL,
    [Name]                NVARCHAR (350)     NOT NULL,
    [TrackNumber]         INT                NOT NULL,
    [WorkName]            NVARCHAR (350)     NULL,
    [HasTimeSyncedLyrics] BIT                NOT NULL,
    [HasLyrics]           BIT                NOT NULL,
    [ContentRating]       NVARCHAR (50)      NULL,
    [ReleaseDate]         DATETIMEOFFSET (7) NULL,
    [DescShort]           NVARCHAR (MAX)     NULL,
    [DescStandard]        NVARCHAR (MAX)     NULL,
    [ImageHeight]         INT                NULL,
    [ImageWidth]          INT                NULL,
    [ImageURL]            NVARCHAR (2000)    NULL,
    [Visible]             BIT                NOT NULL,
    [UploadedBy]          NVARCHAR (250)     NULL,
    [FileName]            NVARCHAR (2000)    NULL,
    [PerformerToken]      INT                NOT NULL,
    [ArtistToken]         INT                NOT NULL,
    [TitleToken]          INT                NOT NULL,
    [AlbumId]             BIGINT             NOT NULL,
    CONSTRAINT [PK_dbo.Song] PRIMARY KEY CLUSTERED ([SongId] ASC)
);


GO
PRINT N'Creating [dbo].[Song].[IX_Song_Slug]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Song_Slug]
    ON [dbo].[Song]([Slug] ASC);


GO
PRINT N'Creating [dbo].[SongExt]...';


GO
CREATE TABLE [dbo].[SongExt] (
    [SongExtId]      BIGINT          NOT NULL,
    [AppleSongId]    BIGINT          NOT NULL,
    [AppleAlbumId]   BIGINT          NOT NULL,
    [GeniusTrackId]  BIGINT          NOT NULL,
    [GeniusAlbumId]  BIGINT          NOT NULL,
    [AppleArtistId]  BIGINT          NOT NULL,
    [GeniusArtistId] BIGINT          NOT NULL,
    [TunebatTrackId] NVARCHAR (250)  NULL,
    [SpotifyUrl]     NVARCHAR (2000) NULL,
    [YoutubeUrl]     NVARCHAR (2000) NULL,
    CONSTRAINT [PK_dbo.SongExt] PRIMARY KEY CLUSTERED ([SongExtId] ASC)
);


GO
PRINT N'Creating [dbo].[SongGenre]...';


GO
CREATE TABLE [dbo].[SongGenre] (
    [SongId]  BIGINT NOT NULL,
    [GenreId] BIGINT NOT NULL,
    CONSTRAINT [PK_dbo.SongGenre] PRIMARY KEY CLUSTERED ([SongId] ASC, [GenreId] ASC)
);


GO
PRINT N'Creating [dbo].[SongTrait]...';


GO
CREATE TABLE [dbo].[SongTrait] (
    [SongTraitId]      BIGINT             NOT NULL,
    [Acousticness]     NVARCHAR (25)      NULL,
    [BPM]              NVARCHAR (25)      NULL,
    [Camelot]          NVARCHAR (25)      NULL,
    [Danceability]     NVARCHAR (25)      NULL,
    [Energy]           NVARCHAR (25)      NULL,
    [Happiness]        NVARCHAR (25)      NULL,
    [Instrumentalness] NVARCHAR (25)      NULL,
    [MusicKey]         NVARCHAR (25)      NULL,
    [Liveness]         NVARCHAR (25)      NULL,
    [Loudness]         NVARCHAR (25)      NULL,
    [Speechiness]      NVARCHAR (25)      NULL,
    [DateAdded]        DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_dbo.SongTrait] PRIMARY KEY CLUSTERED ([SongTraitId] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsEvent]...';


GO
ALTER TABLE [dbo].[AppAnalyticsEvent]
    ADD DEFAULT (sysdatetimeoffset()) FOR [EventDateTime];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT (sysdatetimeoffset()) FOR [EventDateTime];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [IsDesktop];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [IsMobile];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [IsTablet];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [IsTouchEnabled];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [IsWebSocket];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [Latitude];


GO
PRINT N'Creating unnamed constraint on [dbo].[AppAnalyticsRequest]...';


GO
ALTER TABLE [dbo].[AppAnalyticsRequest]
    ADD DEFAULT ((0)) FOR [Longitude];


GO
PRINT N'Creating unnamed constraint on [dbo].[Playlist]...';


GO
ALTER TABLE [dbo].[Playlist]
    ADD DEFAULT ('') FOR [PlaylistType];


GO
PRINT N'Creating unnamed constraint on [dbo].[Playlist]...';


GO
ALTER TABLE [dbo].[Playlist]
    ADD DEFAULT ('') FOR [Url];


GO
PRINT N'Creating unnamed constraint on [dbo].[Playlist]...';


GO
ALTER TABLE [dbo].[Playlist]
    ADD DEFAULT ('') FOR [ParamId];


GO
PRINT N'Creating unnamed constraint on [dbo].[Playlist]...';


GO
ALTER TABLE [dbo].[Playlist]
    ADD DEFAULT ((0)) FOR [IsChart];


GO
PRINT N'Creating unnamed constraint on [dbo].[Playlist]...';


GO
ALTER TABLE [dbo].[Playlist]
    ADD DEFAULT ((0)) FOR [TrackCount];


GO
PRINT N'Creating [dbo].[FK_dbo.AAAspNetUserClaim_dbo.AAAspNetUser_IdentityUser_Id]...';


GO

PRINT N'Creating [dbo].[FK_dbo.AlbumGenre_dbo.Genre_GenerId]...';


GO
ALTER TABLE [dbo].[AlbumGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.AlbumGenre_dbo.Genre_GenerId] FOREIGN KEY ([GenreId]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating [dbo].[FK_dbo.AlbumGenre_dbo.Album_AlbumId]...';


GO
ALTER TABLE [dbo].[AlbumGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.AlbumGenre_dbo.Album_AlbumId] FOREIGN KEY ([AlbumId]) REFERENCES [dbo].[Album] ([AlbumId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistAlbum_dbo.Artist_ArtistId]...';


GO
ALTER TABLE [dbo].[ArtistAlbum] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistAlbum_dbo.Artist_ArtistId] FOREIGN KEY ([ArtistId]) REFERENCES [dbo].[Artist] ([ArtistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistAlbum_dbo.Album_AlbumId]...';


GO
ALTER TABLE [dbo].[ArtistAlbum] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistAlbum_dbo.Album_AlbumId] FOREIGN KEY ([AlbumId]) REFERENCES [dbo].[Album] ([AlbumId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistGenre_dbo.Artist_ArtistId]...';


GO
ALTER TABLE [dbo].[ArtistGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistGenre_dbo.Artist_ArtistId] FOREIGN KEY ([ArtistId]) REFERENCES [dbo].[Artist] ([ArtistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistGenre_dbo.Genre_GenreId]...';


GO
ALTER TABLE [dbo].[ArtistGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistGenre_dbo.Genre_GenreId] FOREIGN KEY ([GenreId]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistPlaylist_dbo.Playlist_PlaylistId]...';


GO
ALTER TABLE [dbo].[ArtistPlaylist] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistPlaylist_dbo.Playlist_PlaylistId] FOREIGN KEY ([PlaylistId]) REFERENCES [dbo].[Playlist] ([PlaylistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistPlaylist_dbo.Artist_ArtistId]...';


GO
ALTER TABLE [dbo].[ArtistPlaylist] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistPlaylist_dbo.Artist_ArtistId] FOREIGN KEY ([ArtistId]) REFERENCES [dbo].[Artist] ([ArtistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistSong_dbo.Artist_ArtistId]...';


GO
ALTER TABLE [dbo].[ArtistSong] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistSong_dbo.Artist_ArtistId] FOREIGN KEY ([ArtistId]) REFERENCES [dbo].[Artist] ([ArtistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.ArtistSong_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[ArtistSong] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.ArtistSong_dbo.Song_SongId] FOREIGN KEY ([SongId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Creating [dbo].[FK_AspNetRoleClaims_AspNetRoles_RoleId]...';


GO

PRINT N'Creating [dbo].[FK_dbo.Lyric_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[Lyric] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Lyric_dbo.Song_SongId] FOREIGN KEY ([LyricId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerAlbum_dbo.Performer_PerformerId]...';


GO
ALTER TABLE [dbo].[PerformerAlbum] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerAlbum_dbo.Performer_PerformerId] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Performer] ([PerformerId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerAlbum_dbo.Album_AlbumId]...';


GO
ALTER TABLE [dbo].[PerformerAlbum] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerAlbum_dbo.Album_AlbumId] FOREIGN KEY ([AlbumId]) REFERENCES [dbo].[Album] ([AlbumId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerGenre_dbo.Genre_GenreId]...';


GO
ALTER TABLE [dbo].[PerformerGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerGenre_dbo.Genre_GenreId] FOREIGN KEY ([GenreId]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerGenre_dbo.Performer_PerformerId]...';


GO
ALTER TABLE [dbo].[PerformerGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerGenre_dbo.Performer_PerformerId] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Performer] ([PerformerId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerPlaylist_dbo.Performer_PerformerId]...';


GO
ALTER TABLE [dbo].[PerformerPlaylist] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerPlaylist_dbo.Performer_PerformerId] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Performer] ([PerformerId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerPlaylist_dbo.Playlist_PlaylistId]...';


GO
ALTER TABLE [dbo].[PerformerPlaylist] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerPlaylist_dbo.Playlist_PlaylistId] FOREIGN KEY ([PlaylistId]) REFERENCES [dbo].[Playlist] ([PlaylistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerSong_dbo.Performer_PerformerId]...';


GO
ALTER TABLE [dbo].[PerformerSong] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerSong_dbo.Performer_PerformerId] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Performer] ([PerformerId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PerformerSong_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[PerformerSong] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PerformerSong_dbo.Song_SongId] FOREIGN KEY ([SongId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PlaylistGenre_dbo.Genre_GenreId]...';


GO
ALTER TABLE [dbo].[PlaylistGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PlaylistGenre_dbo.Genre_GenreId] FOREIGN KEY ([GenreId]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PlaylistGenre_dbo.Playlist_PlaylistId]...';


GO
ALTER TABLE [dbo].[PlaylistGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PlaylistGenre_dbo.Playlist_PlaylistId] FOREIGN KEY ([PlaylistId]) REFERENCES [dbo].[Playlist] ([PlaylistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PlaylistSong_dbo.Playlist_PlaylistId]...';


GO
ALTER TABLE [dbo].[PlaylistSong] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PlaylistSong_dbo.Playlist_PlaylistId] FOREIGN KEY ([PlaylistId]) REFERENCES [dbo].[Playlist] ([PlaylistId]);


GO
PRINT N'Creating [dbo].[FK_dbo.PlaylistSong_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[PlaylistSong] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.PlaylistSong_dbo.Song_SongId] FOREIGN KEY ([SongId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Creating [dbo].[FK_dbo.Song_dbo.Album_AlbumId]...';


GO
ALTER TABLE [dbo].[Song] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.Song_dbo.Album_AlbumId] FOREIGN KEY ([AlbumId]) REFERENCES [dbo].[Album] ([AlbumId]);


GO
PRINT N'Creating [dbo].[FK_dbo.SongExt_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[SongExt] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SongExt_dbo.Song_SongId] FOREIGN KEY ([SongExtId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Creating [dbo].[FK_dbo.SongGenre_dbo.Genre_GenreId]...';


GO
ALTER TABLE [dbo].[SongGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SongGenre_dbo.Genre_GenreId] FOREIGN KEY ([GenreId]) REFERENCES [dbo].[Genre] ([GenreId]);


GO
PRINT N'Creating [dbo].[FK_dbo.SongGenre_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[SongGenre] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SongGenre_dbo.Song_SongId] FOREIGN KEY ([SongId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Creating [dbo].[FK_dbo.SongTrait_dbo.Song_SongId]...';


GO
ALTER TABLE [dbo].[SongTrait] WITH NOCHECK
    ADD CONSTRAINT [FK_dbo.SongTrait_dbo.Song_SongId] FOREIGN KEY ([SongTraitId]) REFERENCES [dbo].[Song] ([SongId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO

ALTER TABLE [dbo].[AlbumGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.AlbumGenre_dbo.Genre_GenerId];

ALTER TABLE [dbo].[AlbumGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.AlbumGenre_dbo.Album_AlbumId];

ALTER TABLE [dbo].[ArtistAlbum] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistAlbum_dbo.Artist_ArtistId];

ALTER TABLE [dbo].[ArtistAlbum] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistAlbum_dbo.Album_AlbumId];

ALTER TABLE [dbo].[ArtistGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistGenre_dbo.Artist_ArtistId];

ALTER TABLE [dbo].[ArtistGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistGenre_dbo.Genre_GenreId];

ALTER TABLE [dbo].[ArtistPlaylist] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistPlaylist_dbo.Playlist_PlaylistId];

ALTER TABLE [dbo].[ArtistPlaylist] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistPlaylist_dbo.Artist_ArtistId];

ALTER TABLE [dbo].[ArtistSong] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistSong_dbo.Artist_ArtistId];

ALTER TABLE [dbo].[ArtistSong] WITH CHECK CHECK CONSTRAINT [FK_dbo.ArtistSong_dbo.Song_SongId];

ALTER TABLE [dbo].[Lyric] WITH CHECK CHECK CONSTRAINT [FK_dbo.Lyric_dbo.Song_SongId];

ALTER TABLE [dbo].[PerformerAlbum] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerAlbum_dbo.Performer_PerformerId];

ALTER TABLE [dbo].[PerformerAlbum] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerAlbum_dbo.Album_AlbumId];

ALTER TABLE [dbo].[PerformerGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerGenre_dbo.Genre_GenreId];

ALTER TABLE [dbo].[PerformerGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerGenre_dbo.Performer_PerformerId];

ALTER TABLE [dbo].[PerformerPlaylist] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerPlaylist_dbo.Performer_PerformerId];

ALTER TABLE [dbo].[PerformerPlaylist] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerPlaylist_dbo.Playlist_PlaylistId];

ALTER TABLE [dbo].[PerformerSong] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerSong_dbo.Performer_PerformerId];

ALTER TABLE [dbo].[PerformerSong] WITH CHECK CHECK CONSTRAINT [FK_dbo.PerformerSong_dbo.Song_SongId];

ALTER TABLE [dbo].[PlaylistGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.PlaylistGenre_dbo.Genre_GenreId];

ALTER TABLE [dbo].[PlaylistGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.PlaylistGenre_dbo.Playlist_PlaylistId];

ALTER TABLE [dbo].[PlaylistSong] WITH CHECK CHECK CONSTRAINT [FK_dbo.PlaylistSong_dbo.Playlist_PlaylistId];

ALTER TABLE [dbo].[PlaylistSong] WITH CHECK CHECK CONSTRAINT [FK_dbo.PlaylistSong_dbo.Song_SongId];

ALTER TABLE [dbo].[Song] WITH CHECK CHECK CONSTRAINT [FK_dbo.Song_dbo.Album_AlbumId];

ALTER TABLE [dbo].[SongExt] WITH CHECK CHECK CONSTRAINT [FK_dbo.SongExt_dbo.Song_SongId];

ALTER TABLE [dbo].[SongGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.SongGenre_dbo.Genre_GenreId];

ALTER TABLE [dbo].[SongGenre] WITH CHECK CHECK CONSTRAINT [FK_dbo.SongGenre_dbo.Song_SongId];

ALTER TABLE [dbo].[SongTrait] WITH CHECK CHECK CONSTRAINT [FK_dbo.SongTrait_dbo.Song_SongId];


GO
PRINT N'Update complete.';


GO
